travis:
  secure:
    BINSTAR_TOKEN: qeJpAY+76iDx8yMpUmJXyVcdFgv7gBTrDzvPtGKlLj1rQEFewf9bvaEjAxgYqG58VBWlLdueG9E4DBiVnyyMJjQ1E+FqGfvQ7zrm120llNkn9Etsii6hBeyhwfLmA3y0GsjsoKl9DSdeq/gIlL30HwZVV1jJnJxNqQfxgaZgdQgqF/juz2jnK9Nt5nAfsmBF2+kpOIHN0M9QLoQeJoUF5tkR0OAjzbFd1wrtb0UmZm7pBRAi4q6UYhSAxQ1xq0HaiExuVwtARfDgIPjVOESzJhDEGSK/zxITJueX6fSxLg9h7jKRvLHEzbkZvgzdNHzdD2aT4VdMOjl1nLVCmDoZxHJEPxdkGdreseqX3tIJBeyT5ftCePwpVu6TL/DPVOrF7EdLh856hKhcS+o9Mijtb7QWz7945XKYoQlca+osflET4H4/lXwADDuInyCrOFSHKWPRQJTrEQ9+e7xbyo+PnhdQJZx5G8H2+nO/LSjZrm3PZk+ICKNjyeb35m3xHX6Z8dL9TaZ3qoTU6WUIaaTCvWs6+oTj7AsKsSXA6tl+fCMP2KW/HoZ2aEdnqN6Sv3J1ljuYah48SMlcKS8dsDu08I8QnzogVC3iOHCm34wRY6lcy4ZQLhzkdQZlsqJz1JySkv7eBR53K7SBOXogkMF/wu5dlLZevjZUtko4LhlXYyE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
